# Generated by Django 5.2.16 on 2026-08-03 19:43

import django.db.models.deletion
import study_materials.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('departments', '0001_initial'),
        ('semesters', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to=study_materials.models.study_material_upload_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='study_materials/thumbnails/')),
                ('material_type', models.CharField(choices=[('PDF', 'PDF Document'), ('DOCX', 'Word Document'), ('PPT', 'PowerPoint'), ('XLSX', 'Excel Spreadsheet'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('ZIP', 'ZIP Archive'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('visibility', models.CharField(choices=[('ALL', 'All Students'), ('COURSE', 'Specific Course'), ('SEMESTER', 'Specific Semester'), ('SUBJECT', 'Specific Subject')], default='ALL', max_length=15)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='courses.course')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='departments.department')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='semesters.semester')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='subjects.subject')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='MaterialDownloadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_downloads', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='study_materials.studymaterial')),
            ],
            options={
                'ordering': ['-download_date'],
            },
        ),
    ]
