# Generated by Django 5.2.16 on 2026-07-24 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TF', 'True / False'), ('FILL', 'Fill in the Blank'), ('SHORT', 'Short Answer'), ('LONG', 'Long Answer'), ('CODING', 'Coding Problem')], db_index=True, default='MCQ', max_length=10)),
                ('chapter', models.CharField(blank=True, max_length=150, null=True)),
                ('topic', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('marks', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], db_index=True, default='MEDIUM', max_length=10)),
                ('prompt_text', models.TextField(help_text='Question text or statement')),
                ('option_a', models.CharField(blank=True, max_length=500, null=True)),
                ('option_b', models.CharField(blank=True, max_length=500, null=True)),
                ('option_c', models.CharField(blank=True, max_length=500, null=True)),
                ('option_d', models.CharField(blank=True, max_length=500, null=True)),
                ('correct_answer', models.TextField(help_text='For MCQ: A/B/C/D. For T/F: True/False. For Fill/Short: exact answer.')),
                ('explanation', models.TextField(blank=True, help_text='Solution explanation for student result review', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='question_images/')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Question Bank',
                'ordering': ['subject', '-created_at'],
                'indexes': [models.Index(fields=['subject', 'difficulty', 'question_type'], name='questions_q_subject_ee8e0d_idx')],
            },
        ),
    ]
