# Generated by Django 5.2.16 on 2026-07-24 17:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='certificates/qr_codes/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/pdfs/')),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='exams.examattempt')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-issue_date'],
            },
        ),
    ]
