# Generated by Django 5.2.16 on 2026-08-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('email_otp', models.CharField(max_length=6)),
                ('phone_otp', models.CharField(max_length=6)),
                ('pending_data', models.JSONField(help_text='Serialized registration form data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Registration OTP',
                'verbose_name_plural': 'Registration OTPs',
                'ordering': ['-created_at'],
            },
        ),
    ]
