# Generated by Django 5.2.16 on 2026-08-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_registrationotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationotp',
            name='session_key',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
