# Generated by Django 5.2.16 on 2026-08-02 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_registrationotp_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otptoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='RegistrationOTP',
        ),
        migrations.DeleteModel(
            name='OTPToken',
        ),
    ]
