# Generated by Django 5.2.16 on 2026-07-24 17:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('total_marks', models.DecimalField(decimal_places=2, default=100.0, max_digits=6)),
                ('passing_marks', models.DecimalField(decimal_places=2, default=40.0, max_digits=6)),
                ('negative_marking', models.DecimalField(decimal_places=2, default=0.0, help_text='Negative marks per wrong objective answer e.g. 0.25', max_digits=4)),
                ('shuffle_questions', models.BooleanField(default=True)),
                ('shuffle_options', models.BooleanField(default=True)),
                ('attempt_limit', models.PositiveIntegerField(default=1)),
                ('password', models.CharField(blank=True, help_text='Optional passcode for exam entry', max_length=50, null=True)),
                ('instructions', models.TextField(default='Read all questions carefully. Do not switch tabs or exit full-screen mode during the exam.')),
                ('is_published', models.BooleanField(default=False)),
                ('max_violations', models.PositiveIntegerField(default=3, help_text='Auto-submit exam after this number of anti-cheat violations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
                ('questions', models.ManyToManyField(blank=True, related_name='exams', to='questions.question')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('TIMED_OUT', 'Timed Out'), ('DISQUALIFIED', 'Disqualified (Violations)')], db_index=True, default='IN_PROGRESS', max_length=20)),
                ('total_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_passed', models.BooleanField(default=False)),
                ('violations_count', models.PositiveIntegerField(default=0)),
                ('is_evaluated', models.BooleanField(default=False)),
                ('question_order', models.JSONField(blank=True, default=list)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Attempt',
                'verbose_name_plural': 'Exam Attempts',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='AttemptViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('TAB_SWITCH', 'Tab Switch'), ('WINDOW_BLUR', 'Window Blur / Focus Lost'), ('FULLSCREEN_EXIT', 'Exited Full Screen'), ('COPY_PASTE', 'Copy / Paste Attempt'), ('REFRESH', 'Page Refresh')], max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='exams.examattempt')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['is_published', 'start_time', 'end_time'], name='exams_exam_is_publ_3180b1_idx'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('passing_marks__lte', models.F('total_marks'))), name='exam_passing_marks_lte_total'),
        ),
    ]
