# Generated by Django 5.2.16 on 2026-08-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='auto_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='cheating_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
